#!/usr/bin/env node
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { basename, dirname, extname, resolve } from 'node:path'

const cTypes = new Map([
  ['void','void'], ['bool','bool'], ['int','int64_t'], ['i64','int64_t'], ['u64','uint64_t'],
  ['usize','size_t'], ['isize','ptrdiff_t'], ['float','double'], ['f64','double'], ['string','noqeri_abi_string']
])
const nqrTypes = new Set(['void','bool','int','i64','u64','usize','isize','float','f64','string'])
function ident(value, kind) {
  if (typeof value !== 'string' || !/^[A-Za-z_][A-Za-z0-9_]*$/.test(value)) throw new Error(`invalid ${kind}: ${String(value)}`)
  return value
}
function type(value) {
  if (!nqrTypes.has(value)) throw new Error(`unsupported binding type ${value}; use scalar ABI types or introduce an explicit stable layout first`)
  return value
}
function fn(value) {
  ident(value.name, 'function name')
  const params = (value.params || []).map(p => ({ name: ident(p.name, 'parameter name'), type: type(p.type) }))
  return { name: value.name, params, returns: type(value.returns || 'void') }
}
function cSignature(item) {
  const params = item.params.length ? item.params.map(p => `${cTypes.get(p.type)} ${p.name}`).join(', ') : 'void'
  return `${cTypes.get(item.returns)} ${item.name}(${params})`
}
function nqrSignature(prefix, item) {
  const params = item.params.map(p => `${p.name}: ${p.type}`).join(', ')
  return `${prefix} function ${item.name}(${params})${item.returns === 'void' ? '' : `: ${item.returns}`}`
}
function guardName(moduleName) { return `NOQERI_BINDINGS_${moduleName.replace(/[^A-Za-z0-9]/g, '_').toUpperCase()}_H` }

async function main() {
  const args = process.argv.slice(2)
  const input = resolve(args.find(x => !x.startsWith('--')) || 'ffi.json')
  const outDir = resolve(args.find(x => x.startsWith('--out='))?.slice(6) || dirname(input))
  const raw = JSON.parse(await readFile(input, 'utf8'))
  if (raw.schema !== 1) throw new Error('binding interface requires schema: 1')
  const moduleName = raw.module || basename(input, extname(input))
  if (!/^[A-Za-z_][A-Za-z0-9_.]*$/.test(moduleName)) throw new Error(`invalid module name ${moduleName}`)
  const imports = (raw.imports || []).map(fn)
  const exports = (raw.exports || []).map(fn)
  await mkdir(outDir, { recursive: true })

  const guard = guardName(moduleName)
  const header = [
    '/* Generated by noqeri-bindgen. Do not hand-edit. */',
    `#ifndef ${guard}`, `#define ${guard}`, '#include <stdbool.h>', '#include <stddef.h>', '#include <stdint.h>', '#include "noqeri/abi.h"', '',
    '/*',
    ' * The ABI-v2 embedding API in noqeri/abi.h is stable.',
    ' * The function declarations below describe native symbols and are intentionally',
    ' * gated until the selected Noqeri backend declares a C-compatible native ABI.',
    ' */',
    '#if defined(NOQERI_EXPERIMENTAL_NATIVE_EXPORT_ABI)',
    ...imports.map(x => `${cSignature(x)};`),
    ...exports.map(x => `${cSignature(x)};`),
    '#endif', '', `#endif /* ${guard} */`, ''
  ].join('\n')

  const nqr = [
    '// Generated by noqeri-bindgen. Do not hand-edit.',
    `module ${moduleName}.bindings`, '',
    '// Native-symbol bindings are backend/target specific until the portable C ABI shim is complete.',
    ...imports.map(x => `${nqrSignature('extern', x)};`),
    '',
    '// Export declarations are documentation signatures. Implement these names in the owning Noqeri module.',
    ...exports.map(x => `// ${nqrSignature('export', x)};`), ''
  ].join('\n')

  const stem = moduleName.replaceAll('.', '_')
  const headerPath = resolve(outDir, `${stem}.h`)
  const nqrPath = resolve(outDir, `${stem}_bindings.nqr`)
  await writeFile(headerPath, header)
  await writeFile(nqrPath, nqr)
  console.log(JSON.stringify({ input, header: headerPath, noqeri: nqrPath, imports: imports.length, exports: exports.length, native_export_abi: 'experimental' }, null, 2))
}
main().catch(error => { console.error(`noqeri-bindgen: ${error.message}`); process.exit(2) })
