import { mkdir, readFile, writeFile, readdir, stat } from 'node:fs/promises'
import { dirname, join, resolve, basename } from 'node:path'
import { performance } from 'node:perf_hooks'

export function statusMessage(status) {
  return new Map([
    [-10, 'unterminated string literal'],
    [-11, 'unterminated block comment'],
    [-20, 'unbalanced parentheses'],
    [-21, 'unbalanced brackets'],
    [-22, 'unbalanced braces'],
    [-40, 'unsafe operation used outside an unsafe boundary'],
    [-41, 'malformed unsafe declaration or block'],
    [-100, 'unexpected syntax'],
    [-101, 'invalid import'],
    [-102, 'invalid declaration'],
    [-103, 'empty source file'],
  ]).get(Number(status)) || `compiler check failed with status ${status}`
}

function lineInfo(text, offset) {
  const before = text.slice(0, Math.max(0, offset))
  const line = before.split('\n').length
  const start = before.lastIndexOf('\n') + 1
  const end = text.indexOf('\n', offset)
  const sourceLine = text.slice(start, end < 0 ? text.length : end)
  return { line, column: offset - start + 1, sourceLine }
}

export function diagnosticFor(text, status, file = '<source>') {
  let offset = 0
  if (Number(status) === -40 || Number(status) === -41) {
    const match = /\b(?:asm|intrinsic|volatile|extern)\b|\bas\s+\*/.exec(text)
    if (match) offset = match.index
  } else if (Number(status) === -10) {
    offset = Math.max(0, text.lastIndexOf('"'))
  } else if (Number(status) === -11) {
    offset = Math.max(0, text.lastIndexOf('/*'))
  } else if (Number(status) === -20) {
    offset = Math.max(0, text.lastIndexOf('('))
  } else if (Number(status) === -21) {
    offset = Math.max(0, text.lastIndexOf('['))
  } else if (Number(status) === -22) {
    offset = Math.max(0, Math.max(text.lastIndexOf('{'), text.lastIndexOf('}')))
  }
  const info = lineInfo(text, offset)
  const caret = `${' '.repeat(Math.max(0, info.column - 1))}^`
  let hint = ''
  if (Number(status) === -40) hint = '\n\nThis operation crosses Noqeri\'s low-level safety boundary.\nTry wrapping the smallest auditable region in:\n    unsafe { ... }\nFor FFI declarations, `unsafe extern function ...` is also accepted.'
  if (Number(status) === -41) hint = '\n\n`unsafe` must introduce `unsafe { ... }` or qualify an `extern` declaration.'
  return `${file}:${info.line}:${info.column}: error: ${statusMessage(status)}\n\n${String(info.line).padStart(4)} | ${info.sourceLine}\n     | ${caret}${hint}`
}

function indentationDelta(line) {
  let open = 0, close = 0, inString = false, escape = false
  for (let i = 0; i < line.length; i++) {
    const c = line[i], n = line[i + 1]
    if (inString) {
      if (escape) escape = false
      else if (c === '\\') escape = true
      else if (c === '"') inString = false
      continue
    }
    if (c === '"') { inString = true; continue }
    if (c === '/' && n === '/') break
    if (c === '{') open++
    if (c === '}') close++
  }
  return { open, close }
}

export function formatSource(source) {
  const lines = source.replace(/\r\n?/g, '\n').split('\n')
  const out = []
  let depth = 0
  for (const raw of lines) {
    const trimmedRight = raw.replace(/[\t ]+$/g, '')
    const trimmed = trimmedRight.trimStart()
    if (!trimmed) { if (out.length && out[out.length - 1] !== '') out.push(''); continue }
    const { open, close } = indentationDelta(trimmed)
    const leadingClose = trimmed.startsWith('}') ? 1 : 0
    const lineDepth = Math.max(0, depth - leadingClose)
    out.push(`${' '.repeat(lineDepth * 4)}${trimmed}`)
    depth = Math.max(0, depth + open - close)
  }
  while (out.length && out[out.length - 1] === '') out.pop()
  return `${out.join('\n')}\n`
}

export async function formatFile(path, checkOnly = false) {
  const before = await readFile(path, 'utf8')
  const after = formatSource(before)
  if (checkOnly) return before === after
  if (before !== after) await writeFile(path, after)
  return before === after
}

export function docsFromSource(source, file = '') {
  const moduleName = source.match(/^\s*module\s+([A-Za-z_][A-Za-z0-9_.]*)/m)?.[1] || basename(file || 'module.nqr', '.nqr')
  const exported = [...source.matchAll(/^\s*export\s+function\s+([A-Za-z_][A-Za-z0-9_]*)\s*(<[^\n{]+>)?\s*\(([^)]*)\)\s*(?::\s*([^\s{]+))?/gm)]
  const records = [...source.matchAll(/^\s*record\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{/gm)]
  let output = `# ${moduleName}\n\nGenerated by \`noqeri doc\`.\n\n`
  if (records.length) {
    output += '## Records\n\n'
    for (const match of records) output += `- \`${match[1]}\`\n`
    output += '\n'
  }
  output += '## Exported functions\n\n'
  if (!exported.length) output += '_No exported functions._\n'
  for (const match of exported) {
    const generic = match[2] || ''
    const result = match[4] || 'void'
    output += `### ${match[1]}\n\n\`function ${match[1]}${generic}(${match[3]}): ${result}\`\n\n`
  }
  return output
}

export async function generateDocs(path, outputPath = '') {
  const source = await readFile(path, 'utf8')
  const docs = docsFromSource(source, path)
  if (outputPath) await writeFile(outputPath, docs)
  return docs
}

export async function findProject(start = process.cwd()) {
  let current = resolve(start)
  try { if (!(await stat(current)).isDirectory()) current = dirname(current) } catch {}
  for (;;) {
    const candidate = join(current, 'project.nqr')
    try { await stat(candidate); return candidate } catch {}
    const parent = dirname(current)
    if (parent === current) throw new Error('project.nqr not found')
    current = parent
  }
}

export async function createProject(name, directory = name) {
  if (!/^[A-Za-z0-9_-]+$/.test(name)) throw new Error('project name may contain letters, digits, _ and -')
  const root = resolve(directory)
  await mkdir(join(root, 'src'), { recursive: true })
  await mkdir(join(root, 'tests'), { recursive: true })
  const manifest = `project {\n    name: "${name}"\n    version: "0.1.0"\n    edition: "2026"\n    entry: "src/main.nqr"\n    profile: "app"\n}\n\ndependencies {\n}\n`
  const main = 'function main(): int {\n    return 0\n}\n'
  const test = 'function smoke_test(): bool {\n    return true\n}\n'
  await writeFile(join(root, 'project.nqr'), manifest, { flag: 'wx' })
  await writeFile(join(root, 'src', 'main.nqr'), main, { flag: 'wx' })
  await writeFile(join(root, 'tests', 'smoke_test.nqr'), test, { flag: 'wx' })
  return root
}

function dependenciesBlock(text) {
  const match = /\bdependencies\s*\{/.exec(text)
  if (!match) return null
  let depth = 1, inString = false, escape = false
  for (let i = match.index + match[0].length; i < text.length; i++) {
    const c = text[i]
    if (inString) { if (escape) escape = false; else if (c === '\\') escape = true; else if (c === '"') inString = false; continue }
    if (c === '"') { inString = true; continue }
    if (c === '{') depth++
    if (c === '}' && --depth === 0) return { start: match.index, bodyStart: match.index + match[0].length, end: i }
  }
  throw new Error('unterminated dependencies block')
}

export async function removeDependency(coordinate, manager) {
  const project = await findProject()
  const text = await readFile(project, 'utf8')
  const block = dependenciesBlock(text)
  if (!block) throw new Error('dependencies block not found')
  const body = text.slice(block.bodyStart, block.end)
  const escaped = coordinate.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const lineRx = new RegExp(`^\\s*[A-Za-z_][A-Za-z0-9_]*\\s*:\\s*"${escaped}@[^"]+"\\s*\\n?`, 'm')
  if (!lineRx.test(body)) throw new Error(`dependency not declared: ${coordinate}`)
  const nextBody = body.replace(lineRx, '')
  await writeFile(project, text.slice(0, block.bodyStart) + nextBody + text.slice(block.end))
  await manager.installProject()
}

export async function auditProject(manager) {
  const project = await findProject()
  const root = dirname(project)
  const lockPath = join(root, 'noqeri.lock')
  const lock = await readFile(lockPath, 'utf8')
  const findings = []
  const seen = new Set()
  if (!lock.startsWith('noqeri-lock 3\n')) findings.push({ severity: 'error', message: 'lockfile is not noqeri-lock 3' })
  for (const line of lock.split('\n')) {
    if (!line.startsWith('package ')) continue
    const parts = line.trim().split(/\s+/)
    if (parts.length !== 6) { findings.push({ severity: 'error', message: `malformed lock entry: ${line}` }); continue }
    const [, alias, coordinate, version, integrity, entry] = parts
    if (seen.has(coordinate)) findings.push({ severity: 'error', message: `duplicate locked coordinate: ${coordinate}` })
    seen.add(coordinate)
    if (!/^sha256:[0-9a-f]{64}$/.test(integrity)) findings.push({ severity: 'error', message: `invalid integrity for ${coordinate}@${version}` })
    if (!entry || entry.includes('..')) findings.push({ severity: 'error', message: `unsafe entry path for ${coordinate}@${version}` })
    try {
      const pkg = await manager.fetchPackage(coordinate, version)
      if (pkg.integrity !== integrity) findings.push({ severity: 'error', message: `lock/cache hash disagreement for ${coordinate}@${version}` })
    } catch (error) {
      findings.push({ severity: 'error', message: `${coordinate}@${version}: ${error.message}` })
    }
  }
  if (!seen.size) findings.push({ severity: 'info', message: 'project has no locked dependencies' })
  return findings
}

export async function doctor() {
  const checks = []
  const nodeMajor = Number(process.versions.node.split('.')[0])
  checks.push({ ok: nodeMajor >= 20, name: 'Node.js 20+', detail: process.version })
  try { const project = await findProject(); checks.push({ ok: true, name: 'project.nqr', detail: project }) } catch (error) { checks.push({ ok: false, name: 'project.nqr', detail: error.message }) }
  checks.push({ ok: true, name: 'platform', detail: `${process.platform}/${process.arch}` })
  checks.push({ ok: true, name: 'offline mode', detail: process.env.NOQERI_OFFLINE === '1' ? 'enabled' : 'disabled' })
  checks.push({ ok: Boolean(process.env.NOQERI_STAGE0), name: 'trusted stage-0 seed', detail: process.env.NOQERI_STAGE0 || 'not configured (required only to rebuild stage 1)' })
  return checks
}

export async function collectNqrFiles(root) {
  const result = []
  async function walk(path) {
    for (const entry of await readdir(path, { withFileTypes: true })) {
      const child = join(path, entry.name)
      if (entry.isDirectory()) await walk(child)
      else if (entry.isFile() && entry.name.endsWith('.nqr')) result.push(child)
    }
  }
  await walk(root)
  return result.sort()
}

export async function benchmarkCheck(compiler, source, iterations = 100) {
  const count = Math.max(1, Math.min(100000, Number(iterations) || 100))
  const started = performance.now()
  let status = 0
  for (let i = 0; i < count; i++) status = Number(compiler.stage1CheckSource(source))
  return { iterations: count, status, millis: performance.now() - started }
}
