#!/usr/bin/env node
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, existsSync, copyFileSync, statSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { basename, join, resolve } from 'node:path'
import { spawnSync } from 'node:child_process'

const opts = Object.fromEntries(process.argv.slice(2).map(x => { const [k,v='true']=x.replace(/^--/,'').split('='); return [k,v] }))
const cases=Math.max(1,Number(opts.cases||250)),seed=Number(opts.seed||0x4e515246)>>>0,timeout=Math.max(50,Number(opts.timeout||1500))
const artifactRoot=resolve(opts.artifacts||'build/fuzz-artifacts'),replay=opts.replay?resolve(opts.replay):''
const exe=process.platform==='win32'?'noqeri.exe':'noqeri',noqeri=process.env.NOQERI_NATIVE||resolve('build',exe)
if(!existsSync(noqeri)){console.error(`fuzz-all: ${noqeri} is missing; build Noqeri first`);process.exit(2)}
let state=seed||1
function rnd(){state^=state<<13;state^=state>>>17;state^=state<<5;return state>>>0}
function pick(xs){return xs[rnd()%xs.length]}
function bytes(max=768){const n=rnd()%max,out=Buffer.alloc(n);for(let i=0;i<n;i++)out[i]=rnd()&0xff;return out}
function nonEmptyBytes(max=768){const value=bytes(max);return value.length?value:Buffer.from([0])}
function mutateText(seedText){const alphabet='(){}[]<>+-*/%=!&|,:;.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_ \n\t"\\';let s=seedText;const edits=1+(rnd()%32);for(let e=0;e<edits;e++){const at=s.length?rnd()%s.length:0,op=rnd()%5;if(op===0)s=s.slice(0,at)+pick(alphabet)+s.slice(at);else if(op===1&&s.length)s=s.slice(0,at)+s.slice(at+1);else if(op===2&&s.length)s=s.slice(0,at)+pick(alphabet)+s.slice(at+1);else if(op===3)s=s.slice(0,at)+pick(['function','record','import','let','const','while','repeat','return','unsafe','null','move','comptime','atomic.load','0','999999999999999999999'])+s.slice(at);else if(s.length){const width=1+(rnd()%Math.min(24,s.length)),start=rnd()%Math.max(1,s.length-width+1),chunk=s.slice(start,start+width);s=s.slice(0,at)+chunk+s.slice(at)}}return s}
function byteArrayLiteral(buffer){return[...buffer].map(x=>`${x} as u8`).join(',')}
function parserHarness(buffer){const literal=byteArrayLiteral(buffer);return `import "../../Lib/std/sql.nqr"\nimport "../../Lib/std/url.nqr"\nimport "../../Lib/std/http.nqr"\nimport "../../Lib/std/dns.nqr"\n\nlet data: [u8; ${buffer.length}] = [${literal}]\nlet view: []u8 = slice(data)\nlet decoded: [u8; ${Math.max(8,buffer.length*3+8)}]\nsql_count_placeholders(view)\nsql_has_unterminated_quote(view)\nsql_identifier_valid(view)\nurl_has_scheme(view)\nurl_percent_encoded_len(view)\nurl_percent_decode(view, slice(decoded))\ndns_name_valid(view)\nlet i: usize = 0 as usize\nwhile i < len(view) { http_is_token_char(view[i]) i = i + 1 as usize }\nprint(0)\n`}
function formatAwareObject(){const out=nonEmptyBytes(1024),kind=rnd()%4;if(kind===0&&out.length>=4)Buffer.from([0x7f,0x45,0x4c,0x46]).copy(out,0);else if(kind===1&&out.length>=4)Buffer.from([0xcf,0xfa,0xed,0xfe]).copy(out,0);else if(kind===2&&out.length>=2)Buffer.from([0x64,0x86]).copy(out,0);return out}
const sourceCorpus=['module fuzz.seed\nrecord Pair { left: int, right: int }\nfunction add(a: int, b: int): int { return a + b }\nlet x: int = add(1, 2)\nprint(x)\n','const base: int = 4\nfunction twice(x: int): int { return x * 2 }\nlet x: int = comptime(twice(base))\nprint(x)\n','let owner: int = 7\n{ let view: *int = &owner print(*view) }\nlet next: int = move(owner)\nprint(next)\n','record Job { id: u64, state: u64 }\nlet jobs: [Job; 2]\nlet i: usize = 0 as usize\nwhile i < len(jobs) { i = i + 1 as usize }\n']
const nqdSeed='table users { id: int key, name: text required }\ndelete users\ninsert users { id: 1, name: "Ada" }\nselect users\n',manifestSeed='package { name: "fuzz/project" version: "0.0.1" edition: "2026" entry: "main.nqr" profile: "application" target: "x86_64-unknown-none" }\n'
const root=mkdtempSync(join(tmpdir(),'noqeri-fuzz-')),generatedRoot=resolve('build','fuzz-generated');mkdirSync(generatedRoot,{recursive:true});const crashes=[],signatures=new Set(),started=Date.now()
function persistCrash(crash){mkdirSync(artifactRoot,{recursive:true});const id=`${Date.now()}-${crashes.length}`,saved=[];for(const arg of crash.args){try{if(!existsSync(arg)||!statSync(arg).isFile())continue;const target=join(artifactRoot,`${id}-${basename(arg)}`);copyFileSync(arg,target);saved.push(target)}catch{}}const metadata=join(artifactRoot,`${id}.json`);const source=saved.find(x=>x.endsWith('.nqr'));writeFileSync(metadata,JSON.stringify({...crash,seed,saved,replay:source?`node Tools/fuzz/fuzz-all.mjs --replay=${source}`:null},null,2)+'\n');return metadata}
function run(label,args,expected=new Set([0,1])){const r=spawnSync(noqeri,args,{encoding:'utf8',timeout,maxBuffer:4*1024*1024}),timedOut=r.error?.code==='ETIMEDOUT',signalCrash=r.signal&&!['SIGTERM'].includes(r.signal),badExit=r.status!==null&&!expected.has(r.status);if(timedOut||signalCrash||badExit||r.error&&!timedOut){const stderr=(r.stderr||'').slice(0,4000),signature=`${label}|${r.status}|${r.signal}|${stderr.split(/\r?\n/)[0]||r.error?.message||''}`;if(!signatures.has(signature)){signatures.add(signature);const crash={label,args,status:r.status,signal:r.signal,timedOut,error:r.error?.message||'',stderr};crashes.push(crash);crash.artifact=persistCrash(crash)}return false}return true}
function replaySource(path){if(!existsSync(path)){console.error(`fuzz-all: replay file does not exist: ${path}`);return 2}let ok=true;ok=run('replay-lexer',['lex',path])&&ok;ok=run('replay-check',['check',path])&&ok;ok=run('replay-nir',['nir',path])&&ok;console.log(JSON.stringify({result:ok?'ok':'crash',replay:path,seed,crashes},null,2));return ok?0:1}
try{if(replay)process.exitCode=replaySource(replay);else{let completed=0;for(let i=0;i<cases;i++){const source=join(root,`case-${i}.nqr`);writeFileSync(source,mutateText(sourceCorpus[i%sourceCorpus.length]));run('lexer',['lex',source]);run('parser+type-checker+ownership+borrow+safety',['check',source]);run('lowerer',['nir',source]);const nqd=join(root,`case-${i}.nqd`),db=join(root,`case-${i}.nqdb`);writeFileSync(nqd,i%3===0?mutateText(nqdSeed):bytes(512).toString('latin1'));run('database/.nqd parser',['db',nqd,db]);const manifest=join(root,`project-${i}.nqr`);writeFileSync(manifest,mutateText(manifestSeed));run('package manifest parser',['manifest',manifest]);const parserInput=i%2===0?Buffer.from(mutateText("SELECT * FROM users WHERE name = '?' https://example.test/a%20b"),'utf8'):nonEmptyBytes(384),parserSource=join(generatedRoot,`parsers-${i}.nqr`);writeFileSync(parserSource,parserHarness(parserInput));run('sql+url+dns+http parsers',['run',parserSource]);const object=join(root,`object-${i}.o`);writeFileSync(object,formatAwareObject());run('object-loader+linker',['link',join(root,`out-${i}`),object]);completed=i+1;if(crashes.length)break}const elapsedMs=Math.max(1,Date.now()-started);if(crashes.length){console.error(JSON.stringify({result:'crash',seed,completedCases:completed,crashes,artifacts:artifactRoot},null,2));process.exitCode=1}else console.log(JSON.stringify({result:'ok',seed,cases,elapsed_ms:elapsedMs,cases_per_second:Number((cases*1000/elapsedMs).toFixed(2)),targets:['lexer','parser/type-checker/ownership/borrow/safety','lowerer','database/.nqd','package-manifest','sql/url/dns/http','object-loader/linker']}))}}finally{rmSync(root,{recursive:true,force:true});rmSync(generatedRoot,{recursive:true,force:true})}
