#include "noe.hpp"
#include <cctype>
#include <filesystem>
#include <iostream>
#include <optional>
#include <sstream>
#include <string>
#include <unordered_map>

namespace noe { namespace {
std::string jsonEscape(const std::string&s){std::ostringstream out;for(unsigned char c:s){switch(c){case'\\':out<<"\\\\";break;case'\"':out<<"\\\"";break;case'\n':out<<"\\n";break;case'\r':out<<"\\r";break;case'\t':out<<"\\t";break;default:if(c<0x20){out<<"\\u";const char*h="0123456789abcdef";out<<"00"<<h[c>>4]<<h[c&15];}else out<<static_cast<char>(c);}}return out.str();}
std::optional<std::string>jsonString(const std::string&body,const std::string&key){std::string needle="\""+key+"\"";auto p=body.find(needle);if(p==std::string::npos)return std::nullopt;p=body.find(':',p+needle.size());if(p==std::string::npos)return std::nullopt;++p;while(p<body.size()&&std::isspace(static_cast<unsigned char>(body[p])))++p;if(p>=body.size()||body[p]!='\"')return std::nullopt;++p;std::string out;while(p<body.size()){char c=body[p++];if(c=='\"')return out;if(c=='\\'&&p<body.size()){char e=body[p++];switch(e){case'n':out+='\n';break;case'r':out+='\r';break;case't':out+='\t';break;case'\"':out+='\"';break;case'\\':out+='\\';break;case'/':out+='/';break;default:out+=e;}}else out+=c;}return std::nullopt;}
std::optional<std::string>rawId(const std::string&body){auto p=body.find("\"id\"");if(p==std::string::npos)return std::nullopt;p=body.find(':',p+4);if(p==std::string::npos)return std::nullopt;++p;while(p<body.size()&&std::isspace(static_cast<unsigned char>(body[p])))++p;if(p>=body.size())return std::nullopt;if(body[p]=='\"'){auto e=p+1;bool esc=false;while(e<body.size()){if(!esc&&body[e]=='\"')return body.substr(p,e-p+1);esc=!esc&&body[e]=='\\';if(body[e]!='\\')esc=false;++e;}return std::nullopt;}auto e=p;while(e<body.size()&&(std::isdigit(static_cast<unsigned char>(body[e]))||body[e]=='-'))++e;return e>p?std::optional<std::string>(body.substr(p,e-p)):std::nullopt;}
bool readMessage(std::string&body){std::string line;std::size_t length=0;while(std::getline(std::cin,line)){if(!line.empty()&&line.back()=='\r')line.pop_back();if(line.empty())break;const std::string h="Content-Length:";if(line.rfind(h,0)==0)length=static_cast<std::size_t>(std::stoul(line.substr(h.size())));}if(!std::cin||length==0)return false;body.assign(length,'\0');std::cin.read(body.data(),static_cast<std::streamsize>(length));return static_cast<std::size_t>(std::cin.gcount())==length;}
void send(const std::string&body){std::cout<<"Content-Length: "<<body.size()<<"\r\n\r\n"<<body<<std::flush;}
std::optional<std::filesystem::path>uriPath(const std::string&uri){if(uri.rfind("file://",0)!=0)return std::nullopt;std::string value=uri.substr(7),decoded;for(std::size_t i=0;i<value.size();++i){if(value[i]=='%'&&i+2<value.size()){auto hex=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return-1;};int hi=hex(value[i+1]),lo=hex(value[i+2]);if(hi>=0&&lo>=0){decoded+=static_cast<char>((hi<<4)|lo);i+=2;continue;}}decoded+=value[i];}
#ifdef _WIN32
if(decoded.size()>2&&decoded[0]=='/'&&std::isalpha(static_cast<unsigned char>(decoded[1]))&&decoded[2]==':')decoded.erase(decoded.begin());
#endif
return std::filesystem::path(decoded);}
CompileResult compileDocument(const std::string&uri,const std::string&text){if(auto path=uriPath(uri))return WorkspaceCompiler{}.compileOverlay(*path,text);return compileSource(text);}
void publishDiagnostics(const std::string&uri,const std::string&text){auto result=compileDocument(uri,text);std::ostringstream out;out<<"{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\""<<jsonEscape(uri)<<"\",\"diagnostics\":[";bool first=true;for(const auto&d:result.diagnostics.items()){if(d.span.source>1)continue;if(!first)out<<',';first=false;auto line=d.span.line?d.span.line-1:0;auto col=d.span.column?d.span.column-1:0;out<<"{\"range\":{\"start\":{\"line\":"<<line<<",\"character\":"<<col<<"},\"end\":{\"line\":"<<line<<",\"character\":"<<(col+1)<<"}},\"severity\":1,\"code\":\""<<jsonEscape(d.code)<<"\",\"source\":\"noqeri\",\"message\":\""<<jsonEscape(d.message)<<"\"}";}out<<"]}}";send(out.str());}
std::string formatResponse(const std::string&id,const std::string&text){Diagnostics d;auto formatted=Formatter{}.format(text,d);if(d.hasErrors())return"{\"jsonrpc\":\"2.0\",\"id\":"+id+",\"result\":null}";return"{\"jsonrpc\":\"2.0\",\"id\":"+id+",\"result\":[{\"range\":{\"start\":{\"line\":0,\"character\":0},\"end\":{\"line\":2147483647,\"character\":0}},\"newText\":\""+jsonEscape(formatted)+"\"}]}";}
} // namespace
int LanguageServer::run(){bool shutdown=false;std::string body;std::unordered_map<std::string,std::string>open;while(readMessage(body)){auto method=jsonString(body,"method");if(!method)continue;auto id=rawId(body);if(*method=="initialize"){auto rid=id.value_or("null");send("{\"jsonrpc\":\"2.0\",\"id\":"+rid+",\"result\":{\"capabilities\":{\"textDocumentSync\":1,\"documentFormattingProvider\":true},\"serverInfo\":{\"name\":\"noqeri Language Server\",\"version\":\""+std::string(NOQERI_COMPILER_VERSION)+"\"}}}");}else if(*method=="initialized")continue;else if(*method=="shutdown"){shutdown=true;send("{\"jsonrpc\":\"2.0\",\"id\":"+id.value_or("null")+",\"result\":null}");}else if(*method=="exit")return shutdown?0:1;else if(*method=="textDocument/didOpen"||*method=="textDocument/didChange"){auto uri=jsonString(body,"uri"),text=jsonString(body,"text");if(uri&&text){open[*uri]=*text;publishDiagnostics(*uri,*text);}}else if(*method=="textDocument/didClose"){if(auto uri=jsonString(body,"uri")){open.erase(*uri);send("{\"jsonrpc\":\"2.0\",\"method\":\"textDocument/publishDiagnostics\",\"params\":{\"uri\":\""+jsonEscape(*uri)+"\",\"diagnostics\":[]}}");}}else if(*method=="textDocument/formatting"&&id){auto uri=jsonString(body,"uri");if(uri){auto it=open.find(*uri);if(it!=open.end())send(formatResponse(*id,it->second));else if(auto path=uriPath(*uri)){try{send(formatResponse(*id,readTextFile(*path)));}catch(...){send("{\"jsonrpc\":\"2.0\",\"id\":"+*id+",\"result\":null}");}}}}else if(id)send("{\"jsonrpc\":\"2.0\",\"id\":"+*id+",\"result\":null}");}return 0;}
} // namespace noe
