#include "noe.hpp"
#include <filesystem>
#include <functional>
#include <system_error>
#include <unordered_set>

namespace noe {
bool ModuleGraph::load(const std::filesystem::path&root,Diagnostics&diagnostics){modules_.clear();sources_.clear();byCanonicalPath_.clear();ModuleId rootId=0;return loadOne(root,diagnostics,&rootId)&&!diagnostics.hasErrors();}
bool ModuleGraph::loadOne(const std::filesystem::path&input,Diagnostics&diagnostics,ModuleId*out){std::error_code ec;const auto canonical=std::filesystem::weakly_canonical(input,ec);if(ec||!std::filesystem::exists(canonical)){diagnostics.error("NQR-M6000",{},"module source not found: "+input.string(),"check import paths relative to the importing file");return false;}const auto key=canonical.generic_string();if(auto found=byCanonicalPath_.find(key);found!=byCanonicalPath_.end()){if(out)*out=found->second;return true;}const ModuleId id=static_cast<ModuleId>(modules_.size());const SourceId sourceId=static_cast<SourceId>(sources_.size()+1);byCanonicalPath_[key]=id;std::string text;try{text=readTextFile(canonical);}catch(const std::exception&error){diagnostics.error("NQR-M6001",{},error.what());return false;}diagnostics.registerSource(sourceId,canonical.string());sources_.push_back(SourceFile{sourceId,canonical,text});Lexer lexer(text,diagnostics,sourceId,false);auto tokens=lexer.lex();if(diagnostics.hasErrors())return false;Parser parser(std::move(tokens),diagnostics);Program ast=parser.parse();if(diagnostics.hasErrors())return false;ModuleUnit unit;unit.id=id;unit.source=sourceId;unit.path=canonical;unit.ast=ast;for(const auto&statement:ast.statements)if(auto module=std::dynamic_pointer_cast<ModuleStmt>(statement)){unit.declaredName=module->name;break;}modules_.push_back(std::move(unit));for(const auto&statement:ast.statements){auto imported=std::dynamic_pointer_cast<ImportStmt>(statement);if(!imported)continue;std::filesystem::path child=imported->path;if(child.extension().empty())child+=".nqr";if(child.is_relative())child=canonical.parent_path()/child;ModuleId childId=0;if(!loadOne(child,diagnostics,&childId))return false;modules_[id].imports.push_back(childId);}if(out)*out=id;return true;}
Program ModuleGraph::mergedProgram()const{Program merged;if(modules_.empty())return merged;std::unordered_set<ModuleId>visited;std::function<void(ModuleId)>append=[&](ModuleId id){if(visited.count(id)||id>=modules_.size())return;visited.insert(id);for(const auto dep:modules_[id].imports)append(dep);for(const auto&statement:modules_[id].ast.statements){if(std::dynamic_pointer_cast<ImportStmt>(statement))continue;merged.statements.push_back(statement);}};append(0);return merged;}
} // namespace noe
