#include "noe.hpp"
#include <algorithm>
#include <fstream>
#include <map>
#include <regex>
#include <sstream>
namespace noe { namespace { std::optional<std::string> field(const std::string& text,const std::string& key){std::regex re("\\b"+key+"\\s*:\\s*\\\"([^\\\"]*)\\\"");std::smatch m;if(std::regex_search(text,m,re))return m[1].str();return std::nullopt;} std::string block(const std::string& text,const std::string& name){auto p=text.find(name);if(p==std::string::npos)return{};p=text.find('{',p);if(p==std::string::npos)return{};int depth=0;std::size_t start=p+1;for(std::size_t i=p;i<text.size();++i){if(text[i]=='{')++depth;else if(text[i]=='}'&&--depth==0)return text.substr(start,i-start);}return{};} std::uint64_t fnv1a(const std::string&s){std::uint64_t h=1469598103934665603ull;for(unsigned char c:s){h^=c;h*=1099511628211ull;}return h;} }
std::optional<ProjectManifest> PackageManager::loadManifest(const std::filesystem::path& path,Diagnostics& diagnostics)const{std::ifstream in(path);if(!in){diagnostics.error("NQR-PKG6000",{},"project manifest not found: "+path.string());return std::nullopt;}std::ostringstream out;out<<in.rdbuf();auto text=out.str();if(text.find("project")==std::string::npos||text.find('{')==std::string::npos){diagnostics.error("NQR-PKG6001",{},"project.nqr must contain a project { ... } block");return std::nullopt;}ProjectManifest m;if(auto v=field(text,"name"))m.name=*v;if(auto v=field(text,"version"))m.version=*v;if(auto v=field(text,"entry"))m.entry=*v;if(auto v=field(text,"profile"))m.profile=*v;if(auto v=field(text,"target"))m.target=*v;auto deps=block(text,"dependencies");if(!deps.empty()){std::regex pair("([A-Za-z_][A-Za-z0-9_.-]*)\\s*:\\s*\\\"([^\\\"]+)\\\"");for(auto it=std::sregex_iterator(deps.begin(),deps.end(),pair);it!=std::sregex_iterator();++it)m.dependencies[(*it)[1].str()]=(*it)[2].str();}return m;}
bool PackageManager::writeLock(const ProjectManifest& manifest,const std::filesystem::path& path,Diagnostics& diagnostics)const{std::ofstream out(path,std::ios::trunc);if(!out){diagnostics.error("NQR-PKG6002",{},"cannot write lock file: "+path.string());return false;}std::map<std::string,std::string> sorted(manifest.dependencies.begin(),manifest.dependencies.end());out<<"noqeri-lock 1\n";out<<"project "<<manifest.name<<' '<<manifest.version<<"\n";for(const auto&[name,version]:sorted){std::ostringstream descriptor;descriptor<<name<<'@'<<version;out<<"dependency "<<name<<' '<<version<<" fnv1a64:"<<std::hex<<fnv1a(descriptor.str())<<std::dec<<"\n";}return true;}
bool PackageManager::createProject(const std::filesystem::path& directory,const std::string& name,Diagnostics& diagnostics)const{std::error_code ec;if(std::filesystem::exists(directory)&&!std::filesystem::is_empty(directory,ec)){diagnostics.error("NQR-PKG6003",{},"project directory is not empty: "+directory.string());return false;}std::filesystem::create_directories(directory/"src",ec);std::filesystem::create_directories(directory/"tests",ec);if(ec){diagnostics.error("NQR-PKG6004",{},"cannot create project directories: "+ec.message());return false;}{std::ofstream p(directory/"project.nqr");if(!p){diagnostics.error("NQR-PKG6005",{},"cannot create project.nqr");return false;}p<<"project {\n    name: \""<<name<<"\"\n    version: \"0.1.0\"\n    entry: \"src/main.nqr\"\n    profile: \"app\"\n    target: \"freestanding-x86_64\"\n}\n";}{std::ofstream m(directory/"src"/"main.nqr");if(!m){diagnostics.error("NQR-PKG6006",{},"cannot create src/main.nqr");return false;}m<<"print(\"Hello from noqeri\")\n";}ProjectManifest manifest;manifest.name=name;manifest.version="0.1.0";return writeLock(manifest,directory/"noqeri.lock",diagnostics);} }
