#pragma once
#include "version.hpp"
#include "diagnostics.hpp"
#include "types.hpp"
#include "ast.hpp"
#include "nir.hpp"
#include "modules.hpp"
#include "packages.hpp"
#include "targets.hpp"
#include "runtime.hpp"
#include "generics.hpp"
#include "web.hpp"
#include "compiler.hpp"
#include "tools.hpp"
namespace noqeri = noe;
